In [ ]:
# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Upload Data**

In [ ]:
cd /content/drive/My Drive/Dr. Yasser

/content/drive/My Drive/Dr. Yasser

In [ ]:
!ls

1976-2018-house2-unzipped.csv  creditcard_Corre2.csv  creditcard.csv
1976-2018-senate.csv	       creditcard_Corre3.csv  creditcard_Entropy.csv
2012_US_elect_county.csv       creditcard_Corre4.csv  president-1976-2016.csv
Correlation.csv		       creditcard_Corre.csv

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_df = pd.read_csv("./creditcard.csv")
data_df.head()

   Time        V1        V2        V3  ...        V8        V9       V10  Amount
0   0.0 -1.359807 -0.072781  2.536347  ...  0.098698  0.363787  0.090794  149.62
1   0.0  1.191857  0.266151  0.166480  ...  0.085102 -0.255425 -0.166974    2.69
2   1.0 -1.358354 -1.340163  1.773209  ...  0.247676 -1.514654  0.207643  378.66
3   1.0 -0.966272 -0.185226  1.792993  ...  0.377436 -1.387024 -0.054952  123.50
4   2.0 -1.158233  0.877737  1.548718  ... -0.270533  0.817739  0.753074   69.99

[5 rows x 12 columns]

# **Correlation**

In [ ]:
import scipy.stats

In [ ]:

x = data_df['Time']
y = data_df['V1']
scipy.stats.pearsonr(x, y)    # Pearson's r

(0.11739630597792308, 0.0)

In [ ]:
x = data_df['Time']
y = data_df['V2']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.010593327121062871, 1.5720602373346465e-08)

In [ ]:
x = data_df['Time']
y = data_df['V3']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.41961817221155195, 0.0)

In [ ]:
x = data_df['Time']
y = data_df['V3']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.41961817221155195, 0.0)

In [ ]:
x = data_df['Time']
y = data_df['V4']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.10526020544596626, 0.0)

In [ ]:
x = data_df['Time']
y = data_df['V5']
scipy.stats.pearsonr(x, y)    # Pearson's r

(0.17307212331241073, 0.0)

In [ ]:
x = data_df['Time']
y = data_df['V6']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.06301647037310384, 1.9781095527908298e-248)

In [ ]:
x = data_df['Time']
y = data_df['V7']
scipy.stats.pearsonr(x, y)    # Pearson's r

(0.08471437480619652, 0.0)

In [ ]:
x = data_df['Time']
y = data_df['V8']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.03694943468997647, 1.3008565346501943e-86)

In [ ]:
x = data_df['Time']
y = data_df['V9']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.008660433698228439, 3.8022836230786966e-06)

In [ ]:
x = data_df['Time']
y = data_df['V10']
scipy.stats.pearsonr(x, y)    # Pearson's r

(0.030616628592372866, 4.876718024480923e-60)

In [ ]:
x = data_df['Time']
y = data_df['Amount']
scipy.stats.pearsonr(x, y)    # Pearson's r

(-0.010596373389029254, 1.5572510616181674e-08)

In [ ]:
correlation_df = pd.read_csv("./Correlation.csv")
correlation_df.head()

    Field  Correlation
0      V3    -0.419618
1      V4    -0.105260
2      V6    -0.063016
3      V8    -0.036949
4  Amount    -0.010596

In [ ]:
import plotly.express as px

In [ ]:

df_corre = pd.read_csv("./creditcard_Corre4.csv")
fig = px.parallel_coordinates(df_corre, color="V3",
                              color_continuous_scale=px.colors.diverging.Tealrose,
                              color_continuous_midpoint=2)
fig.show()

# **Entropy**

In [ ]:
import collections
import math

In [ ]:
from scipy.stats import entropy

In [ ]:
pd_series = pd.Series(data_df['Time'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

16.68954952561777

In [ ]:

pd_series = pd.Series(data_df['Amount'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

11.497523774654313

In [ ]:

pd_series = pd.Series(data_df['V1'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.028917396596736

In [ ]:

pd_series = pd.Series(data_df['V2'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.028931441195358

In [ ]:

pd_series = pd.Series(data_df['V3'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.02894548579398

In [ ]:

pd_series = pd.Series(data_df['V4'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.028924418896047

In [ ]:

pd_series = pd.Series(data_df['V5'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.02894548579398

In [ ]:

pd_series = pd.Series(data_df['V6'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.0289060025211

In [ ]:

pd_series = pd.Series(data_df['V7'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.028903351998114

In [ ]:

pd_series = pd.Series(data_df['V8'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.02882782795901

In [ ]:

pd_series = pd.Series(data_df['V9'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.02893846349467

In [ ]:

pd_series = pd.Series(data_df['V10'])
m = len(pd_series)
bases = collections.Counter([tmp_base for tmp_base in pd_series])

shannon_entropy_value = 0
for base in bases:
    # number of residues
    n_i = bases[base]
    # n_i (# residues type i) / M (# residues in column)
    p_i = n_i / float(m)
    entropy_i = p_i * (math.log(p_i, 2))
    shannon_entropy_value += entropy_i

print(shannon_entropy_value * -1)

18.02886293945557

In [ ]:
import plotly.express as px

In [ ]:

df_corre = pd.read_csv("./creditcard_Entropy.csv")
fig = px.parallel_coordinates(df_corre, color="Amount",
                              color_continuous_scale=px.colors.diverging.Tealrose,
                              color_continuous_midpoint=2)
fig.show()